export const CHANGE_LEFT_COLUMN = "CHANGE_LEFT_COLUMN";
export const REMOVE_LEFT_CARD = "REMOVE_LEFT_CARD";
export const MOVE_LEFT_CARD = "MOVE_LEFT_CARD";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
